# **Computational Drug Discovery [Part 1] Download Bioactivity Data**

Chanin Nantasenamat

[*'Data Professor' YouTube channel*](http://youtube.com/dataprofessor)

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

---

## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.
[Data as of March 25, 2020; ChEMBL version 26].

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [1]:
! pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.3.3-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.19)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.7.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-26.2.1-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.11.8)
Collecting url-normalize>=2.0 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-3.0.1-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.16.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 2.2 MB/s eta 0:00:00
Downloading requests_cache-1.3.3-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 6.9 MB/s eta 0:00:00
Downloading cattrs-26.2.1-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.8/74.8 kB 5.6 MB/s eta 0:00:00
Downloading url_normalize-3.0.1-py3-none-any.whl (18 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-26.2.1 chembl_webresource_client-0.10.9 requests-cache-1.3.3 url-normalize-3.0.1

## **Importing libraries**

In [2]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

/usr/local/lib/python3.13/dist-packages/chembl_webresource_client/__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __version__ = __import__('pkg_resources').get_distribution('chembl_webresource_client').version

## **Search for Target protein**

### **Target search for Glutamine**

In [8]:
# Target search for glutamine
target = new_client.target
target_query = target.search('glutamine')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Rattus norvegicus,Asparagine synthetase [glutamine-hydrolyzing],15.0,False,CHEMBL2303,"[{'accession': 'P49088', 'component_descriptio...",SINGLE PROTEIN,10116
1,[],Mus musculus,GMP synthase [glutamine-hydrolyzing],15.0,False,CHEMBL2765,"[{'accession': 'Q3THK7', 'component_descriptio...",SINGLE PROTEIN,10090
2,[],Homo sapiens,GMP synthase [glutamine-hydrolyzing],15.0,False,CHEMBL5721,"[{'accession': 'P49915', 'component_descriptio...",SINGLE PROTEIN,9606
3,[],Mus musculus,Protein-glutamine gamma-glutamyltransferase 2,15.0,False,CHEMBL2079853,"[{'accession': 'P21981', 'component_descriptio...",SINGLE PROTEIN,10090
4,[],Mus musculus,Asparagine synthetase [glutamine-hydrolyzing],15.0,False,CHEMBL3243906,"[{'accession': 'Q61024', 'component_descriptio...",SINGLE PROTEIN,10090
5,[],Cavia cutleri,Protein-glutamine gamma-glutamyltransferase 2,15.0,False,CHEMBL3988613,"[{'accession': 'P08587', 'component_descriptio...",SINGLE PROTEIN,10144
6,[],Homo sapiens,Asparagine synthetase [glutamine-hydrolyzing],14.0,False,CHEMBL3120,"[{'accession': 'P08243', 'component_descriptio...",SINGLE PROTEIN,9606
7,[],Escherichia coli K-12,Glutamine synthetase,14.0,False,CHEMBL3789,"[{'accession': 'P0A9C5', 'component_descriptio...",SINGLE PROTEIN,83333
8,[],Salmonella typhimurium (strain LT2 / SGSC1412 ...,Glutamine synthetase,14.0,False,CHEMBL5089,"[{'accession': 'P0A1P6', 'component_descriptio...",SINGLE PROTEIN,99287
9,[],Glycine max,Glutamine synthetase,14.0,False,CHEMBL5218,"[{'accession': 'Q43760', 'component_descriptio...",SINGLE PROTEIN,3847
10,[],Homo sapiens,Glutamine,14.0,False,CHEMBL2366039,[],SMALL MOLECULE,9606
11,[],Spinacia oleracea,Glutamine synthetase,14.0,False,CHEMBL2366402,"[{'accession': 'A1YYP7', 'component_descriptio...",SINGLE PROTEIN,3562
12,[],Lolium perenne,Glutamine synthetase,14.0,False,CHEMBL2366423,"[{'accession': 'C5IW59', 'component_descriptio...",SINGLE PROTEIN,4522
13,[],Oryza sativa,Glutamine synthetase,14.0,False,CHEMBL2366486,"[{'accession': 'Q01HZ7', 'component_descriptio...",SINGLE PROTEIN,4530
14,[],Plasmodium falciparum,GMP synthase [glutamine-hydrolyzing],14.0,False,CHEMBL4523484,"[{'accession': 'Q8IJR9', 'component_descriptio...",SINGLE PROTEIN,5833
15,[],Homo sapiens,Protein-glutamine gamma-glutamyltransferase E,13.0,False,CHEMBL3363,"[{'accession': 'Q08188', 'component_descriptio...",SINGLE PROTEIN,9606
16,[],Homo sapiens,Protein-glutamine gamma-glutamyltransferase K,13.0,False,CHEMBL2810,"[{'accession': 'P22735', 'component_descriptio...",SINGLE PROTEIN,9606
17,[],Homo sapiens,Glutamine synthetase,13.0,False,CHEMBL4612,"[{'accession': 'P15104', 'component_descriptio...",SINGLE PROTEIN,9606
18,[],Homo sapiens,Protein-glutamine gamma-glutamyltransferase,13.0,False,CHEMBL2730,"[{'accession': 'P21980', 'component_descriptio...",SINGLE PROTEIN,9606
19,[],Nicotiana tabacum,Glutamine synthetase,13.0,False,CHEMBL2366496,"[{'accession': 'Q42950', 'component_descriptio...",SINGLE PROTEIN,4097
20,[],Cavia porcellus,Protein-glutamine gamma-glutamyltransferase,13.0,False,CHEMBL3308976,"[{'accession': 'Q7M0F8', 'component_descriptio...",SINGLE PROTEIN,10141
21,[],Homo sapiens,Kynurenine--oxoglutarate transaminase 1,12.0,False,CHEMBL3962,"[{'accession': 'Q16773', 'component_descriptio...",SINGLE PROTEIN,9606
22,[],Homo sapiens,Glutamine--tRNA ligase,12.0,False,CHEMBL3054,"[{'accession': 'P47897', 'component_descriptio...",SINGLE PROTEIN,9606
23,[],Saccharomyces cerevisiae S288c,General amino acid permease AGP1,12.0,False,CHEMBL1741178,"[{'accession': 'P25376', 'component_descriptio...",SINGLE PROTEIN,559292
24,[],Zea mays,"Glutamine synthetase, chloroplastic",12.0,False,CHEMBL2285357,"[{'accession': 'P25462', 'component_descriptio...",SINGLE PROTEIN,4577
25,[],Homo sapiens,Amidophosphoribosyltransferase,12.0,False,CHEMBL2362992,"[{'accession': 'Q06203', 'component_descriptio...",SINGLE PROTEIN,9606
26,[],Escherichia coli (strain K12),Glutamine--tRNA ligase,12.0,False,CHEMBL5291592,"[{'accession': 'P00962', 'component_descriptio...",SINGLE PROTEIN,83333
27,[],Homo sapiens,Multifunctional protein CAD,11.0,False,CHEMBL3093,"[{'accession': 'P27708', 'component_descriptio...",SINGLE PROTEIN,9606
28,[],Mus musculus,Multifunctional protein CAD,11.0,False,CHEMBL2774,"[{'accession': 'B2RQC6', 'component_descriptio...",SINGLE PROTEIN,10090
29,[],Mus musculus,"Glutaminase liver isoform, mitochondrial",11.0,False,CHEMBL2176860,"[{'accession': 'Q571F8', 'component_descriptio...",SINGLE PROTEIN,10090
30,[],Homo sapiens,"Glutaminase liver isoform, mitochondrial",11.0,False,CHEMBL4105730,"[{'accession': 'Q9UI32', 'component_descriptio...",SINGLE PROTEIN,9606
31,[],Homo sapiens,Glutaminase 1/2,11.0,False,CHEMBL4106183,"[{'accession': 'O94925', 'component_descriptio...",PROTEIN FAMILY,9606
32,[],Homo sapiens,Glutamine amidotransferase-like class 1 domain...,11.0,False,CHEMBL5169114,"[{'accession': 'P0DPI2', 'component_descriptio...",SINGLE PROTEIN,9606
33,[],Mus musculus,Coagulation factor XIII A/B chain,11.0,False,CHEMBL6066544,"[{'accession': 'P05160', 'component_descriptio...",PROTEIN COMPLEX,10090
34,[],Homo sapiens,Coagulation factor XIII A chain,10.0,False,CHEMBL4530,"[{'accession': 'P00488', 'component_descriptio...",SINGLE PROTEIN,9606
35,[],Homo sapiens,Protein-glutamine gamma-glutamyltransferase 6,10.0,False,CHEMBL2079852,"[{'accession': 'O95932', 'component_descriptio...",SINGLE PROTEIN,9606
36,[],Homo sapiens,Coagulation factor XIII B chain,10.0,False,CHEMBL3351193,"[{'accession': 'P05160', 'component_descriptio...",SINGLE PROTEIN,9606
37,[],Bos taurus,Coagulation factor XIII A chain,10.0,False,CHEMBL5291510,"[{'accession': 'P12260', 'component_descriptio...",SINGLE PROTEIN,9913
38,[],Homo sapiens,Small glutamine-rich tetratricopeptide repeat-...,10.0,False,CHEMBL6066222,"[{'accession': 'O43765', 'component_descriptio...",SINGLE PROTEIN,9606
39,[],Homo sapiens,Glutamine--fructose-6-phosphate aminotransfera...,9.0,False,CHEMBL1909481,"[{'accession': 'Q06210', 'component_descriptio...",SINGLE PROTEIN,9606
40,[],Homo sapiens,"Glutaminase kidney isoform, mitochondrial",9.0,False,CHEMBL2146302,"[{'accession': 'O94925', 'component_descriptio...",SINGLE PROTEIN,9606
41,[],Rattus norvegicus,"Glutaminase kidney isoform, mitochondrial",9.0,False,CHEMBL4523186,"[{'accession': 'P13264', 'component_descriptio...",SINGLE PROTEIN,10116
42,[],Homo sapiens,"Splicing factor, proline- and glutamine-rich",9.0,False,CHEMBL5725114,"[{'accession': 'P23246', 'component_descriptio...",SINGLE PROTEIN,9606
43,[],Homo sapiens,rRNA 2'-O-methyltransferase fibrillarin,9.0,False,CHEMBL6066942,"[{'accession': 'P22087', 'component_descriptio...",SINGLE PROTEIN,9606

### **Select and retrieve bioactivity data for *Protein-glutamine gamma-glutamyltransferase 2* (fourth entry)**

We will assign the fifth entry (which corresponds to the target protein, *coronavirus 3C-like proteinase*) to the ***selected_target*** variable

In [18]:
selected_target = targets.target_chembl_id[3]
selected_target

'CHEMBL2079853'

Here, we will retrieve only bioactivity data for *Protein-glutamine gamma-glutamyltransferase 2* (CHEMBL2079853) that are reported as IC$_{50}$ values in uM unit.

In [22]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(type="IC50")

In [20]:
df = pd.DataFrame.from_dict(res)

In [21]:
df.head(3)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,11010395,[],CHEMBL2091167,Inhibition of mouse recombinant TG2 by fluores...,B,None,None,BAO_0000190,...,Mus musculus,Protein-glutamine gamma-glutamyltransferase 2,10090,None,None,IC50,uM,UO_0000065,None,0.016
1,None,None,12054596,[],CHEMBL2155214,Inhibition of mouse TGM2,B,None,None,BAO_0000190,...,Mus musculus,Protein-glutamine gamma-glutamyltransferase 2,10090,None,None,IC50,uM,UO_0000065,None,0.055
2,None,None,12177343,[],CHEMBL2214886,Inhibition of mouse transglutaminase 2,B,None,None,BAO_0000190,...,Mus musculus,Protein-glutamine gamma-glutamyltransferase 2,10090,None,None,IC50,uM,UO_0000065,None,6.2

In [23]:
df.standard_type.unique()

array(['IC50'], dtype=object)

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [24]:
df.to_csv('bioactivity_data.csv', index=False)

## **Copying files to Google Drive**

Firstly, we need to mount the Google Drive into Colab so that we can have access to our Google adrive from within Colab.

In [25]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

Next, we create a **data** folder in our **Colab Notebooks** folder on Google Drive.

In [26]:
! mkdir "/content/gdrive/My Drive/Colab Notebooks/data2"

In [27]:
! cp bioactivity_data.csv "/content/gdrive/My Drive/Colab Notebooks/data2"

In [28]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/data2"

total 3
-rw------- 1 root root 2200 Oct  2 05:59 bioactivity_data.csv

Let's see the CSV files that we have so far.

In [30]:
! ls

bioactivity_data.csv  gdrive  sample_data

Taking a glimpse of the **bioactivity_data.csv** file that we've just created.

In [29]:
! head bioactivity_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,modality,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,11010395,[],CHEMBL2091167,Inhibition of mouse recombinant TG2 by fluorescent transamidation assay,B,,,BAO_0000190,BAO_0000357,single protein format,C=CC(=O)Nc1ccc(S(=O)(=O)N2CCN(C(=O)C34CC5CC(CC(C5)C3)C4)CC2)cc1,,,CHEMBL2086255,J Med Chem,2012,"{'bei': '17.04', 'le': '0.33', 'lle': '4.94', 'sei': '8.98'}",,CHEMBL2086528,,CHEMBL2086528,7.80,0,http://www.openphacts.org/units/Nanomolar,1673303,=,1,1,=,,IC50,nM,,16.0,CHEMBL2079853,Mus musculus,Protein-glutamine gamma-glutamyltransferase 2,10090,,,IC50,uM,UO_0000065,,0.016
,,12054596,[],CHEMBL2155214,Inhibition of mouse TGM2,B,,,BAO_0000190,BAO_0000357,single protein format,C=CC(=O)NC1CCN(S(=O)(=O)c2ccc(C(=O)NCCc3ccc(OC)cc3)cc2)CC1,,,CHEMBL2150866,ACS Med Chem Lett,2012,"{'bei': '15.39', 'le': '0.30', 'lle': '5.14', 'sei': '6.93'}",,CHEMBL2152204,,CHEMBL2152204,7.26,0,http://www.openphacts.org/units/Nanomolar,1730816,=,1,1,=,,IC50,nM,,55.0,CHEMBL2079853,Mus musculus,Protein-glutamine gamma-glutamyltransferase 2,10090,,,IC50,uM,UO_0000065,,0.055
,,12177343,[],CHEMBL2214886,Inhibition of mouse transglutaminase 2,B,,,BAO_0000190,BAO_0000357,single protein format,C=CC(=O)NCCCC[C@H](NC(=O)OCc1ccccc1)C(=O)NCC(=O)OC(C)(C)C,,,CHEMBL2203174,ACS Med Chem Lett,2012,"{'bei': '11.64', 'le': '0.22', 'lle': '3.00', 'sei': '4.24'}",,CHEMBL2203476,,CHEMBL2203476,5.21,0,http://www.openphacts.org/units/Nanomolar,1755914,=,1,1,=,,IC50,nM,,6200.0,CHEMBL2079853,Mus musculus,Protein-glutamine gamma-glutamyltransferase 2,10090,,,IC50,uM,UO_0000065,,6.2

## **Handling missing data**
If any compounds has missing value for the **standard_value** column then drop it

In [32]:
df2 = df[df.type.notna()]
df2

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,11010395,[],CHEMBL2091167,Inhibition of mouse recombinant TG2 by fluores...,B,None,None,BAO_0000190,...,Mus musculus,Protein-glutamine gamma-glutamyltransferase 2,10090,None,None,IC50,uM,UO_0000065,None,0.016
1,None,None,12054596,[],CHEMBL2155214,Inhibition of mouse TGM2,B,None,None,BAO_0000190,...,Mus musculus,Protein-glutamine gamma-glutamyltransferase 2,10090,None,None,IC50,uM,UO_0000065,None,0.055
2,None,None,12177343,[],CHEMBL2214886,Inhibition of mouse transglutaminase 2,B,None,None,BAO_0000190,...,Mus musculus,Protein-glutamine gamma-glutamyltransferase 2,10090,None,None,IC50,uM,UO_0000065,None,6.2

Apparently, for this dataset there is no missing data. But we can use the above code cell for bioactivity data of other target protein.

## **Data pre-processing of the bioactivity data**

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [35]:
bioactivity_class = []
for i in df2.value:
  if float(i)*1000 >= 10000:
    bioactivity_class.append("inactive")
  elif float(i)*1000 <= 1000:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

### **Iterate the *molecule_chembl_id* to a list**

In [36]:
mol_cid = []
for i in df2.molecule_chembl_id:
  mol_cid.append(i)

### **Iterate *canonical_smiles* to a list**

In [37]:
canonical_smiles = []
for i in df2.canonical_smiles:
  canonical_smiles.append(i)

### **Iterate *standard_value* to a list**

In [38]:
standard_value = []
for i in df2.standard_value:
  standard_value.append(i)

### **Combine the 4 lists into a dataframe**

In [39]:
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value))
df3 = pd.DataFrame( data_tuples,  columns=['molecule_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value'])

In [40]:
df3

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value
0,CHEMBL2086528,C=CC(=O)Nc1ccc(S(=O)(=O)N2CCN(C(=O)C34CC5CC(CC...,active,16.0
1,CHEMBL2152204,C=CC(=O)NC1CCN(S(=O)(=O)c2ccc(C(=O)NCCc3ccc(OC...,active,55.0
2,CHEMBL2203476,C=CC(=O)NCCCC[C@H](NC(=O)OCc1ccccc1)C(=O)NCC(=...,intermediate,6200.0

### **Alternative method**

In [51]:
selection = ['molecule_chembl_id', 'canonical_smiles', 'standard_value']
df3 = df2[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL2086528,C=CC(=O)Nc1ccc(S(=O)(=O)N2CCN(C(=O)C34CC5CC(CC...,16.0
1,CHEMBL2152204,C=CC(=O)NC1CCN(S(=O)(=O)c2ccc(C(=O)NCCc3ccc(OC...,55.0
2,CHEMBL2203476,C=CC(=O)NCCCC[C@H](NC(=O)OCc1ccccc1)C(=O)NCC(=...,6200.0

In [52]:
pd.concat([df3,pd.Series(bioactivity_class)], axis=1)

,molecule_chembl_id,canonical_smiles,standard_value,0
0,CHEMBL2086528,C=CC(=O)Nc1ccc(S(=O)(=O)N2CCN(C(=O)C34CC5CC(CC...,16.0,active
1,CHEMBL2152204,C=CC(=O)NC1CCN(S(=O)(=O)c2ccc(C(=O)NCCc3ccc(OC...,55.0,active
2,CHEMBL2203476,C=CC(=O)NCCCC[C@H](NC(=O)OCc1ccccc1)C(=O)NCC(=...,6200.0,intermediate

Saves dataframe to CSV file

In [46]:
df3.to_csv('bioactivity_preprocessed_data.csv', index=False)

In [47]:
! ls -l

total 16
-rw-r--r-- 1 root root 2200 Oct  2 05:57 bioactivity_data.csv
-rw-r--r-- 1 root root  291 Oct  2 06:08 bioactivity_preprocessed_data.csv
drwx------ 5 root root 4096 Oct  2 05:58 gdrive
drwxr-xr-x 1 root root 4096 Sep 16 13:26 sample_data

Let's copy to the Google Drive

In [49]:
! cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data2"

In [48]:
! ls "/content/gdrive/My Drive/Colab Notebooks/data2"

bioactivity_data.csv

---